name: ml_jupyter

services:
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter-ml
    ports:
      - "9999:8888"
    volumes:
      # 실습코드 폴더 전체를 Jupyter 작업 폴더로 마운트
      - ./실습코드:/home/jovyan/work
      - ./requirements.txt:/tmp/requirements.txt
    command: >
      bash -c "pip install --no-cache-dir -r /tmp/requirements.txt &&
               pip uninstall -y bottleneck numexpr pyarrow &&
               start-notebook.sh --IdentityProvider.token=''"
    restart: unless-stopped
